-- ============================================================
-- UPGRADE: add Action Tracker form fields + action_implementers table
-- ============================================================
-- Safe to run while the app is live: every new column is nullable
-- (or boolean with a default), and action_implementers is a brand new
-- table nothing currently references. No locks on existing rows beyond
-- the brief lock Postgres takes for any ALTER TABLE / CREATE TABLE.

BEGIN;

-- ---- New columns on meeting_actions ----
ALTER TABLE meeting_actions ADD COLUMN title VARCHAR(500);
ALTER TABLE meeting_actions ADD COLUMN issue_challenge TEXT;
ALTER TABLE meeting_actions ADD COLUMN is_key_action BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE meeting_actions ADD COLUMN type_of_action VARCHAR(100);
ALTER TABLE meeting_actions ADD COLUMN date_initiated TIMESTAMPTZ;
ALTER TABLE meeting_actions ADD COLUMN tags JSON;
ALTER TABLE meeting_actions ADD COLUMN assign_to_meeting_id UUID;

ALTER TABLE meeting_actions
    ADD CONSTRAINT fk_meeting_actions_assign_to_meeting
    FOREIGN KEY (assign_to_meeting_id) REFERENCES meetings(id) ON DELETE SET NULL;

CREATE INDEX ix_meeting_actions_assign_to_meeting
    ON meeting_actions (assign_to_meeting_id);

-- ---- New action_implementers table ----
CREATE TABLE action_implementers (
    id UUID PRIMARY KEY,
    action_id UUID NOT NULL,
    user_id UUID,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_action_implementers_action
        FOREIGN KEY (action_id) REFERENCES meeting_actions(id) ON DELETE CASCADE,
    CONSTRAINT fk_action_implementers_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX ix_action_implementers_action_id ON action_implementers (action_id);
CREATE INDEX ix_action_implementers_user_id ON action_implementers (user_id);

COMMIT;

-- After running this manually, tell Alembic this revision is applied
-- WITHOUT re-running its Python upgrade() (which would fail with
-- DuplicateColumn/DuplicateTable errors, same as we saw with 8ecaf039942e):
--
--   alembic stamp <revision_id_from_the_autogenerated_file>
--
-- Only do this if you ran this SQL directly instead of `alembic upgrade head`.
-- If you just let Alembic run the migration normally, you do NOT need to
-- stamp anything — `alembic upgrade head` already updates that bookkeeping
-- for you as part of a normal run.


-- ============================================================
-- ROLLBACK: reverse everything above, in dependency order
-- ============================================================
-- Uncomment and run this block only if you need to undo the upgrade above.

-- BEGIN;
--
-- DROP INDEX IF EXISTS ix_action_implementers_user_id;
-- DROP INDEX IF EXISTS ix_action_implementers_action_id;
-- DROP TABLE IF EXISTS action_implementers;
--
-- DROP INDEX IF EXISTS ix_meeting_actions_assign_to_meeting;
-- ALTER TABLE meeting_actions DROP CONSTRAINT IF EXISTS fk_meeting_actions_assign_to_meeting;
-- ALTER TABLE meeting_actions DROP COLUMN IF EXISTS assign_to_meeting_id;
-- ALTER TABLE meeting_actions DROP COLUMN IF EXISTS tags;
-- ALTER TABLE meeting_actions DROP COLUMN IF EXISTS date_initiated;
-- ALTER TABLE meeting_actions DROP COLUMN IF EXISTS type_of_action;
-- ALTER TABLE meeting_actions DROP COLUMN IF EXISTS is_key_action;
-- ALTER TABLE meeting_actions DROP COLUMN IF EXISTS issue_challenge;
-- ALTER TABLE meeting_actions DROP COLUMN IF EXISTS title;
--
-- COMMIT;


-- Create notifications table
CREATE TABLE IF NOT EXISTS notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    channel VARCHAR(50) NOT NULL,
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    participant_id UUID REFERENCES meeting_participants(id) ON DELETE SET NULL,
    meeting_id UUID REFERENCES meetings(id) ON DELETE SET NULL,
    recipient VARCHAR(255) NOT NULL,
    recipient_name VARCHAR(255),
    subject VARCHAR(255),
    content TEXT NOT NULL,
    template_name VARCHAR(100),
    category VARCHAR(50),
    status VARCHAR(50) DEFAULT 'pending',
    error_message TEXT,
    sent_at TIMESTAMP,
    tracking_id VARCHAR(255),
    is_opened BOOLEAN DEFAULT FALSE,
    opened_at TIMESTAMP,
    open_count INTEGER DEFAULT 0,
    provider_message_id VARCHAR(255),
    extra_data JSONB,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    is_active BOOLEAN DEFAULT TRUE
);

-- Create indexes for better performance
CREATE INDEX idx_notifications_meeting_id ON notifications(meeting_id);
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_channel ON notifications(channel);
CREATE INDEX idx_notifications_status ON notifications(status);
CREATE INDEX idx_notifications_created_at ON notifications(created_at);
CREATE INDEX idx_notifications_tracking_id ON notifications(tracking_id);

ALTER TABLE notifications
ALTER COLUMN channel TYPE notification_channel
USING channel::notification_channel;


ALTER TABLE notifications ALTER COLUMN status DROP DEFAULT;

ALTER TABLE notifications
ALTER COLUMN status TYPE notification_status
USING status::notification_status;

ALTER TABLE notifications
ALTER COLUMN status SET DEFAULT 'pending'::notification_status;






# migrations/versions/xxxx_add_notification_enums.py

"""Add notification enum types

Revision ID: xxxx
Revises: yyyy
Create Date: 2024-01-01 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'xxxx'
down_revision = 'yyyy'
branch_labels = None
depends_on = None

def upgrade():
    # Create enum types
    op.execute("""
        DO $$ 
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_channel') THEN
                CREATE TYPE notification_channel AS ENUM ('email', 'sms', 'whatsapp', 'in_app');
            END IF;
            
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_status') THEN
                CREATE TYPE notification_status AS ENUM ('pending', 'successful', 'failed', 'delivered', 'read');
            END IF;
            
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_category') THEN
                CREATE TYPE notification_category AS ENUM ('meeting_notification', 'action_assignment', 'system_alert', 'reminder', 'other');
            END IF;
        END $$;
    """)
    
    # Convert channel column
    op.execute("""
        ALTER TABLE notifications 
        ALTER COLUMN channel TYPE notification_channel 
        USING channel::notification_channel
    """)
    
    # Convert category column
    op.execute("""
        ALTER TABLE notifications 
        ALTER COLUMN category TYPE notification_category 
        USING category::notification_category
    """)
    
    # Convert status column
    op.execute("ALTER TABLE notifications ALTER COLUMN status DROP DEFAULT")
    op.execute("""
        ALTER TABLE notifications 
        ALTER COLUMN status TYPE notification_status 
        USING status::notification_status
    """)
    op.execute("ALTER TABLE notifications ALTER COLUMN status SET DEFAULT 'pending'::notification_status")
    
    # Add check constraints
    op.execute("""
        ALTER TABLE notifications ADD CONSTRAINT check_notification_channel 
        CHECK (channel IN ('email', 'sms', 'whatsapp', 'in_app'))
    """)
    op.execute("""
        ALTER TABLE notifications ADD CONSTRAINT check_notification_status 
        CHECK (status IN ('pending', 'successful', 'failed', 'delivered', 'read'))
    """)
    op.execute("""
        ALTER TABLE notifications ADD CONSTRAINT check_notification_category 
        CHECK (category IN ('meeting_notification', 'action_assignment', 'system_alert', 'reminder', 'other'))
    """)


def downgrade():
    # Drop defaults and constraints
    op.execute("ALTER TABLE notifications ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE notifications DROP CONSTRAINT IF EXISTS check_notification_channel")
    op.execute("ALTER TABLE notifications DROP CONSTRAINT IF EXISTS check_notification_status")
    op.execute("ALTER TABLE notifications DROP CONSTRAINT IF EXISTS check_notification_category")
    
    # Convert status back
    op.execute("""
        ALTER TABLE notifications 
        ALTER COLUMN status TYPE VARCHAR(50) 
        USING status::VARCHAR(50)
    """)
    op.execute("ALTER TABLE notifications ALTER COLUMN status SET DEFAULT 'pending'")
    
    # Convert category back
    op.execute("""
        ALTER TABLE notifications 
        ALTER COLUMN category TYPE VARCHAR(100) 
        USING category::VARCHAR(100)
    """)
    
    # Convert channel back
    op.execute("""
        ALTER TABLE notifications 
        ALTER COLUMN channel TYPE VARCHAR(50) 
        USING channel::VARCHAR(50)
    """)
    
    # Drop enum types
    op.execute("DROP TYPE IF EXISTS notification_channel CASCADE")
    op.execute("DROP TYPE IF EXISTS notification_status CASCADE")
    op.execute("DROP TYPE IF EXISTS notification_category CASCADE")








    CREATE TYPE notification_channel AS ENUM ('email', 'sms', 'whatsapp');
CREATE TYPE notification_category AS ENUM (
    'auth_verification', 'auth_welcome', 'auth_password_reset',
    'meeting_notification', 'other'
);
CREATE TYPE notification_status AS ENUM ('pending', 'successful', 'failed');

ALTER TABLE notifications
ALTER COLUMN channel TYPE notification_channel
USING channel::notification_channel;

ALTER TABLE notifications
ALTER COLUMN category TYPE notification_category
USING category::notification_category;

ALTER TABLE notifications ALTER COLUMN status DROP DEFAULT;
ALTER TABLE notifications
ALTER COLUMN status TYPE notification_status
USING status::notification_status;
ALTER TABLE notifications
ALTER COLUMN status SET DEFAULT 'pending'::notification_status;



CREATE TABLE action_implementers (
    id UUID PRIMARY KEY,
    action_id UUID NOT NULL REFERENCES meeting_actions(id) ON DELETE CASCADE,
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX ix_action_implementers_action_id ON action_implementers(action_id);
CREATE INDEX ix_action_implementers_user_id ON action_implementers(user_id);